name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Brakeman
        run: gem install brakeman  # Install brakeman globally

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: brakeman --no-pager  # Use global installation

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Ensure bin/importmap exists and is executable
        run: |
          if [ ! -f bin/importmap ]; then
            echo "bin/importmap not found! Generating..."
            bundle exec rails importmap:install
          fi
          chmod +x bin/importmap

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Ensure RuboCop is installed
        run: bundle install --with development

      - name: Run RuboCop Linter
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Ensure bin/rails is executable
        run: |
          if [ ! -f bin/rails ]; then
            echo "bin/rails not found! Generating..."
            bundle exec rails app:update:bin
          fi
          chmod +x bin/rails

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails test
          bundle exec rails test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
